name:                huelang
version:             0.1.0.0
github:              "HueStudios/HueLang"
license:             MIT
author:              "Juan Pablo Ossa Zapata"
maintainer:          "ozjuanpa@gmail.com"
copyright:           "2020 Juan Pablo Ossa Zapata"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/HueStudios/HueLang#readme>

dependencies:
- base >= 4.7 && < 5
- Useful
- containers
- Stack

executables:
  huelang-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - huelang
    - haskeline

library:
  source-dirs: src

tests:
  huelang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - huelang
